apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: three-tier
spec:
  selector:
    app.kubernetes.io/name: todo-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

