apiVersion: v1
kind: Service
metadata:
  name: todo-mongodb-svc
  namespace: three-tier
spec:
  selector:
    app.kubernetes.io/name: todo-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  

