apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  namespace: three-tier
spec:
  selector:
    app.kubernetes.io/name: todo-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  clusterIP: 
  type: LoadBalancer

