apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-todo-app
  namespace: three-tier  
spec:
  rules:
  - host: your-domain.com  # Replace with your domain from GoDaddy
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service  # Replace with your frontend service name
            port:
              number: 3000  # Replace with the port your frontend service listens on
